### PR TITLE
Add tests and fix some revealed errors.

### PR DESCRIPTION
**Pull request by whikloj**

### CODE REVIEW

**Comment by mjordan** [comment]
@whikloj nice work! You'll also need to add a .travis.yml that runs the tests, e.g. https://github.com/mjordan/islandora_datastream_crud/blob/7.x/.travis.yml#L42.

I'll be off the grid until Sept.15 but will take a look at this when I return.

**Comment by whikloj** [comment]
I had initially copied the Islandora travis run, but it appears that your testing matrix only worries about Fedora 3.8.1 but wants all the PHPs from 5.3.3 on. Is that still the case?

**Comment by MarcusBarnes** [comment]
N.B.  - If you need to run Travis against PHP 5.3.3, you'll need to do something like https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/blob/7.x/.travis.yml#L11-L24  This is due to Travis CI no longer using the `precise` build by default (and hence no PHP 5.3 support).

**Comment by whikloj** [comment]
@MarcusBarnes thanks. I'll leave that decision up to @mjordan. Personally I think if we are only testing the latest Fedora, then testing the last 6 versions of PHP is probably overkill. 😄

**Comment by whikloj** [comment]
@mjordan @MarcusBarnes Just a note, to get 5.3.3 and others I had to do this
https://raw.githubusercontent.com/uml-digitalinitiatives/islandora_simple_map/travis_test/.travis.yml

**Comment by whikloj** [comment]
However this is exposing my use of `[]` instead of `array()`. If 5.3.3 support is important, then I can go and change those back.

**Comment by whikloj** [comment]
@mjordan I sure you are still getting back into the groove, but do you know if supporting PHP 5.3.3 is something you still want to do here? 

I ask because I have 3 PRs lined up, so if you want PHP 5.3.3 then I'll remove my use of `[]` for `array()`, and rebase all the PRs. 

If you _don't_ want PHP 5.3.3 then I'll remove it from the Travis testing matrix and rebase all the PRs 😄

**Comment by whikloj** [comment]
@mjordan Also you'll need to turn on this repository in Travis.

**Comment by whikloj** [comment]
@mjordan For this first PR, the keys are 
1. Turn on Travis-CI for this repository, which should get the tests running.
1. Decide if you want to support PHP 5.3.3. I need to either remove 5.3.3 from the testing matrix or remove any use of `[]` arrays.

**Comment by whikloj** [comment]
@mjordan bump, I'm going to be loading our first collection with some map requirements in the new year. I'd love to use your module, but I'm running my fork with all 4 of the PRs in it.

**Comment by mjordan** [comment]
@whikloj I'm super sorry to let this drop. I'll test and merge by end of day tomorrow.

**Comment by whikloj** [comment]
@mjordan for this one, if you enable Travis it will test itself. You really just need to ensure the test coverage is what you want because this is just testing code that is already in the 7.x branch.

The other 3 will need more review/testing.

**Comment by mjordan** [comment]
@whikloj welp, I completely didn't understand your merge order instructions over at https://github.com/mjordan/islandora_simple_map/pull/30#issuecomment-335955011.  I merged this PR and they all got merged. Travis is failing at https://travis-ci.org/mjordan/islandora_simple_map/builds/319734150# but it's not clear (to me) why.

**Comment by mjordan** [comment]
Failure is happening at https://github.com/mjordan/islandora_simple_map/blob/7.x/tests/hooks.test#L113.

**Comment by whikloj** [comment]
@mjordan ok, I'll pull 7.x and see if I can figure out and fix it. You didn't answer whether you want to support PHP 5.3.3 because I still have some square bracket arrays in my code which would need to be removed?

**Comment by mjordan** [comment]
Sorry, yes, we should support PHP 5.3.3.

**Pull request merged**
