### PR TITLE
Use OpenStreetMaps

### LINKED ISSUE #5: Adding support for OpenStreetMap
I can't find much by way of a direct API for using OpenStreetMap similar to how this module uses Google Maps, but the HTML that needs to be generated looks like this:

``` html
<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://www.openstreetmap.org/export/embed.html?bbox=-123.38882446289061%2C49.14555903725487%2C-122.93563842773436%2C49.35353208188311&amp;layer=mapnik&amp;marker=49.24965507167121%2C-123.1622314453125" style="border: 1px solid black"></iframe><br/><small><a href="http://www.openstreetmap.org/?mlat=49.2497&amp;mlon=-123.1622#map=12/49.2497/-123.1622">View Larger Map</a></small>
```

The difficulty in assembling this markup is computing the `bbox` values from the lat/long. A [Perl implementation](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Lon..2Flat._to_bbox) of how to do this is available on the OSM wiki.

### PR DESCRIPTION
**Pull request by whikloj**
Resolves #5 

Google requiring billing information pushed me to get this working.

I haven't implemented pushing the individual tile provider API key onto the tile provider template yet but that raised some questions.

1. Should people be able to provide their own tile provider?
1. How do we choose if there are multiple styles available from a single provider?

But this does work with the OpenStreet Maps tile provider which is only allowed for very few requests. 

Its a start is what I'm saying.

Collection map in Google
simple_maps_gmap

Same map in OSM
simple_maps_osm

Pinging @mjordan @MarcusBarnes and @ruebot (because he didn't want to use his own credit card either).

### CODE REVIEW

**Comment by mjordan** [comment]
@whikloj sweet. I'm travelling at the moment but can give this a test over the weekend.

**Comment by whikloj** [comment]
Ok it seems like to use MapBox you **have** to use their own javascript and CSS files. I thought you could just swap out tile providers but that does not seem to be the case (it does work for Thunderforest). So the question becomes, should we **not** support MapBox or do we abstract the JS.

What this means is each provider provides or uses the default object. This object creates the map, adds markers, etc using an interface of functions and hiding the underlying JS. So if you select Mapbox we load their JS and CSS and use their object to call their functions to create the map, etc.

**Comment by whikloj** [comment]
Uh I lied, I just got MapBox to work. It is limited in what you can do (compared to using the full MapBox GL libraries), but its a start. I'm going to update this PR with the changes I have made to get these 3 tile providers to work.

**Comment by whikloj** [comment]
I think this is ready for now. There are other things I could do (abstract/re-use some javascript, make hooks for the tile providers) but I'm starting small.

**Comment by mjordan** [comment]
OK, will test. Thanks!

**Comment by mjordan** [comment]
@whikloj getting an API key now, sorry to drop testing this.

**Comment by mjordan** [comment]
No need for a key! I just selected OpenStreet Maps as my map type and it worked on a single object display. Anything in particular you want tested?

**Comment by whikloj** [comment]
I don't really know, it seems to work. #5 was your issue so I guess I'm wondering if this covers your use case, is there other stuff you want out of using OpenStreetMaps?

**Comment by whikloj** [comment]
Thanks @ruebot, we are also using this in production to get away from Google's required billing information. http://digitalcollections.lib.umanitoba.ca/islandora/object/uofm%3Apaum_tunnel/maps

**Comment by whikloj** [comment]
I'm also changing this from "Partially resolves" to "Resolves" as I think this is a fairly robust implementation for OpenStreetMaps.

**Comment by mjordan** [comment]
@whikloj @ruebot I'm not clear on at what threshold a key is required. It would be useful to provide at least some guidance (maybe in the description of the key field or in the README) so that people's maps don't stop working suddenly because of throttling. Maybe we should recommend that people get a key just in case? If so, what specific key do they need, as opposed to "you need to get an API key."?

**Comment by mjordan** [comment]
@whikloj agree, this resolves #5. Thanks!

**Comment by whikloj** [comment]
@mjordan Here is the OpenStreetMap [Tile Usage Policy](https://operations.osmfoundation.org/policies/tiles/). It is not definitive, so I would suggest that OpenStreetMap is good as a placeholder or a test situation. MapBox has a Pay-as-you-go plan that gives 50,000 maps per month before you get charged. I think maybe our suggestion would be "you can use the OSM tile server, but if you get popular they might shut you down."

**Comment by mjordan** [comment]
I think adding that to the README would prevent a lot of people asking the question in issue later. Do you mind adding it? Or I can.

**Comment by whikloj** [comment]
I can do that, as I realize I have not updated the README at all to handle all the UI changes as well.

**Comment by whikloj** [comment]
@mjordan With the joys of Github I decided to actually provide the screen shots in the repo. Not sure if thats okay with you.

**Comment by mjordan** [comment]
@whikloj looks great to me. Since @ruebot and I both have tested this, I'm happy to merge it and close #5 any time.

**Comment by whikloj** [comment]
Travis has finally run against this so I think we are good to go

**Comment by whikloj** [comment]
@mjordan sorry discovered a mistake I made that caused @ruebot's settings to get deleted when he implemented this and then ran the `drush updatedb` later. This should allow for that without causing too much havoc. Only thing would be if you got a new Google API key, this would overwrite it with the old one. 🤷‍♂️

**Comment by mjordan** [comment]
OK, can I merge?

**Comment by whikloj** [comment]
@mjordan yeah, if you're happy then I'm happy.

**Comment by mjordan** [comment]
@whikloj thanks a million for working on this, it's a major enhancement.

**Pull request merged**
